# Generated by Django 5.1.1 on 2024-10-02 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_create_date_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufactured_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
