# Generated by Django 5.1.1 on 2024-10-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='publicate',
            field=models.BooleanField(default=True),
        ),
    ]
