# Generated by Django 5.1.1 on 2024-10-22 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_publicate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=255, null=True, unique=True, verbose_name='URL')),
                ('view_count', models.IntegerField(default=0)),
                ('publicate', models.BooleanField(default=True)),
                ('text', models.TextField()),
                ('create_date', models.DateTimeField(default=datetime.datetime.now)),
                ('last_change_date', models.DateTimeField(default=datetime.datetime.now)),
                ('image', models.ImageField(null=True, upload_to='images')),
            ],
        ),
    ]
