# Generated by Django 5.1.1 on 2024-11-04 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_version_options_product_user_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('set_false_published_status', 'Can cancel publicate product'), ('change_description', 'Can change product description'), ('change_category', 'Can change product category')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
