# Generated by Django 5.1.1 on 2024-11-04 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('set_false_product_published_status', 'Can cancel publicate product'), ('change_product_description', 'Can change product description'), ('change_product_category', 'Can change product category')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
